### ISSUE TITLE
`isoWeekday` is not a function

### ISSUE THREAD

**Issue by stockiNail** [chartjs/chartjs-adapter-luxon#22]
I got an error `isoWeekday is not a function` when I try to use the `startOf` method of the adapter.

https://github.com/chartjs/chartjs-adapter-luxon/blob/18d1a9b5cd4a441e135a80c7505d4fb3bf089be9/src/index.js#L75

Having a look to Luxon documentation, the `isoWeekday(weekday)` sounds to belong to Moment and not to Luxon.

The doc https://github.com/moment/luxon/blob/master/docs/moment.md#unit-getters

EDIT
Chart.js version: dist/master
Luxon adapter: 0.2.1
Luxon lib: 1.24.1

**Comment by benmccann** [comment]
Just as a heads up, I don't have time to fix at the moment, but I'll review a PR if you want to take a stab

**Comment by stockiNail** [comment]
@benmccann let me take time because I'm very busy as well but I can try to submit a PR. Ok for you?

**Comment by benmccann** [comment]
Sure. No rush

**Comment by stockiNail** [comment]
@benmccann submitted. Take your time!

**Comment by stockiNail** [comment]
Please Walt for a while because calculation is stil wrong

**Comment by stockiNail** [comment]
@benmccann fixed again in order to:

1.  calculate the right start of week because previously was wrong the calculation when weekday passed as argument was 7 (Sunday)
2. normalized the weekday passed as argument in order to have always a consistent result even if the weekday argument is not between 1 and 7.

**Comment by gabrielcalk** [comment]
Hello, I'm having a problem with ISO Day of Week after I migrated from moment to dayjs. Here's the error:
![image](https://user-images.githubusercontent.com/89816900/175544902-04656b9b-7dee-421e-88e8-6a25d94c79ea.png)

Repo link: https://github.com/gabrielcalk/moment_to_day
