### ISSUE TITLE
Cannot read property '_adapters' of undefined with v3-alpha2

### ISSUE THREAD

**Issue by aalyokhin** [chartjs/chartjs-adapter-luxon#27]
Hey guys. When using 0.2.2 with latest Chart.js 3.0.0-alpha.2 I am getting the following:

`Cannot read property '_adapters' of undefined`

However 0.2.1 works fine. Reproduced on [Codesandbox](https://codesandbox.io/s/chartjs-forked-019se).

**Comment by etimberg** [comment]
I believe this is fixed with #29

**Comment by Codermar** [comment]
I don't think this is fixed. I am seeing the same error with chartjs-adapter-luxon 0.2.2 and 3.0.0-rc.5. You can try the above codesandbox with the rc version and see. @aalyokhin  Have you found a workaround?

**Comment by kurkle** [comment]
It's the v1.0.0--beta,where this is fixed

**Comment by Codermar** [comment]
Thank you for the hint. You are right, 1.0.0-beta.2 does work in my case.
