### ISSUE TITLE
Support for Chart.js v3 - import error: 'chart.js' does not contain a default export (imported as 'Chart')

### ISSUE THREAD

**Issue by kashifshamaz21** [chartjs/chartjs-adapter-luxon#28]
@benmccann I'm trying to use `Chart.js 3.x` with current version of `chartjs-adapter-luxon (v0.2.2)`, and it seems like Chartjs-v3 isn't yet supported.

I get an import error while compiling:
```
./node_modules/chartjs-adapter-luxon/dist/chartjs-adapter-luxon.esm.js
Attempted import error: 'chart.js' does not contain a default export (imported as 'Chart').
``` 
**Module Versions:**
```
"chart.js": "3.0.0-beta.9",
"chartjs-adapter-luxon": "^0.2.2",
```
Is it possible to add support for v3, if the fix is only in making the right import and doesn't need lot of changes? I would be happy to send a PR if you can let me know the scope of change needed here.

**Comment by benmccann** [comment]
I think maybe the last version worked and the current doesn't. Try `"chartjs-adapter-luxon": "0.2.1"`

**Comment by kashifshamaz21** [comment]
@benmccann  Thanks for the quick response. Yes, I tried with `0.2.1` and I didn't see the above compile time error with that version. Would you be able to fix the import error for the latest version as well?

**Comment by iar01** [comment]
Go to 
`./node_modules/react-chartjs-2/es/index.js` and change 
`import Chart from 'chart.js';` 
to 
`import {Chart} from 'chart.js';` it would work
