### ISSUE TITLE
Link on README is broken

### ISSUE THREAD

**Issue by s4m0r4m4** [chartjs/chartjs-adapter-luxon#44]
The "Luxon API docs" link on the README is broken, just fyi.

**Comment by kurkle** [comment]
Fixed by https://github.com/chartjs/chartjs-adapter-luxon/commit/256af99841ba53b34fe8b3946562c734a53b9309 (unwittingly committed directly)

**Comment by s4m0r4m4** [comment]
Cool thanks! Just a suggestion - you may want to consider protecting the master branch against direct commits, all the best!
