### ISSUE TITLE
chartjs-adapter-luxon 1.1.0 is incompatible with luxon 3.0.1

### ISSUE THREAD

**Issue by StephanTLavavej** [chartjs/chartjs-adapter-luxon#61]
I'm seeing the following npm warning when I attempt to update to today's release of luxon 3.0.1:

```
D:\GitHub\chart>npm install luxon@latest
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: stl-status-chart@1.0.0
npm WARN Found: luxon@2.5.0
npm WARN node_modules/luxon
npm WARN   peer luxon@"^1.0.0 || ^2.0.0" from chartjs-adapter-luxon@1.1.0
npm WARN   node_modules/chartjs-adapter-luxon
npm WARN     chartjs-adapter-luxon@"^1.1.0" from the root project
npm WARN   1 more (the root project)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer luxon@"^1.0.0 || ^2.0.0" from chartjs-adapter-luxon@1.1.0
npm WARN node_modules/chartjs-adapter-luxon
npm WARN   chartjs-adapter-luxon@"^1.1.0" from the root project

changed 1 package, and audited 81 packages in 457ms

10 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

This may be related to:

https://github.com/chartjs/chartjs-adapter-luxon/blob/1b1c23073eb364bd5bd25de6161a19be44d5b5fc/package.json#L56

It appears that chartjs-adapter-luxon needs to be updated to accept the luxon 3.x series.

(Thanks again for your great work! I use it in the [microsoft/STL Status Chart](https://microsoft.github.io/STL/). :smile_cat:)

**Comment by stockiNail** [comment]
@StephanTLavavej I don't have a huge experience on npm, therefore I'm not sure, but I think the `peerDependencies` could be:

```javascript
 "luxon": "^1.0.0"
```

because the adapter is declared to work with Luxon greater than 1.0.0 version.

**Comment by stockiNail** [comment]
I have done some tests and the current adapter sounds working properly with Luxon 3.0.1.

**Comment by Cluster2a** [comment]
Same problem here....

![image](https://user-images.githubusercontent.com/84905165/178345672-4cab7e93-3eb3-4361-95ed-b8ffeaf52e6c.png)

**Comment by benmccann** [comment]
>I think the peerDependencies could be:
 "luxon": "^1.0.0"
because the adapter is declared to work with Luxon greater than 1.0.0 version.

That means it must be 1.x version. You'd want it to be `>= 1.0.0` for that. `*` or `>= 0.0.0` would probably work too. Docs for it are here: https://docs.npmjs.com/cli/v6/using-npm/semver#ranges

**Comment by stockiNail** [comment]
@benmccann I had a look to the doc (thanks!). In my opinion, it sounds better to have `"luxon": "*"`, but I'm not aware if the adapter can work with Luxon 0.*.

**Comment by kurkle** [comment]
I'd use `>=1.0.0`

**Comment by claireramming** [comment]
I see the pull request to fix this issue is approved... are there plans to merge it soon?

**Comment by claireramming** [comment]
does this change also need to be released? I'm still getting the same error when I try to install.

**Comment by Cluster2a** [comment]
Same here - still getting the same error.

**Comment by benmccann** [comment]
The change has not been released. You can see that here: https://www.npmjs.com/package/chartjs-adapter-luxon

Perhaps @stockiNail or @kurkle would be able to help with cutting a release

**Comment by stockiNail** [comment]
@benmccann I cannot do anything because I am not a collaborator

**Comment by kurkle** [comment]
Released: https://www.npmjs.com/package/chartjs-adapter-luxon/v/1.2.0
