### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by alberto-schena-gizero** [chartjs/chartjs-adapter-luxon#89]
I am facing the following error when importing the library from an ES module:

![image](https://user-images.githubusercontent.com/62008869/216374334-1e0a2ac4-eeb0-4150-82fd-530bf70d3f25.png)

In addition, VSCode fails to navigate to the js sources when CTRL+clicking the library name.
Both import and navigation errors can be fixed by adding the `main` property in `package.json` as of line 10 in the following:

![image](https://user-images.githubusercontent.com/62008869/216374789-8e28d24c-c563-48ff-a919-8c9fbef09352.png)

**Comment by benmccann** [comment]
This was fixed in https://github.com/chartjs/chartjs-adapter-luxon/pull/85

It may need a new release though. @kurkle would you be able to cut a new release?
